name: Deploy site to server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm  
      - name: Install dependencies
        run: npm ci 
      - name: Build with VitePress
        run: npm run site:build 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-artifact
          path: site/.vitepress/dist/
      - name: Deploy to server over ssh
        uses: easingthemes/ssh-deploy@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} 
          ARGS: "-rlgoDzvc -i" 
          SOURCE: "site/.vitepress/dist/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }} 
          REMOTE_USER: ${{ vars.REMOTE_USER }} 
          TARGET: ${{ vars.REMOTE_TARGET }}
          EXCLUDE: ""